# Generated by Django 4.0.5 on 2022-06-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listened',
            field=models.IntegerField(default=0),
        ),
    ]
